### ISSUE TITLE
Cannot find command handler path. (Only happens on VPS)

### ISSUE THREAD

**Issue by yu4L** [TFAGaming/DiscordJS-V14-Bot-Template#47]
**I cloned your repo on my local machine. Works perfect. Soon as I clone it on my VPS I get a path error:**
```
Error: ENOENT: no such file or directory, scandir './src/commands/'
    at readdirSync (node:fs:1451:3)
    at module.exports (/home/ubuntu/DiscordJS-V14-Bot-Template/src/handlers/commands.js:10:24)
    at module.exports.start (/home/ubuntu/DiscordJS-V14-Bot-Template/src/class/ExtendedClient.js:37:9)
    at Object.<anonymous> (/home/ubuntu/DiscordJS-V14-Bot-Template/src/index.js:6:8)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -2,
  syscall: 'scandir',
  code: 'ENOENT',
  path: './src/commands/'
} Promise {
  <rejected> Error: ENOENT: no such file or directory, scandir './src/commands/'
      at readdirSync (node:fs:1451:3)
      at module.exports (/home/ubuntu/DiscordJS-V14-Bot-Template/src/handlers/commands.js:10:24)
      at module.exports.start (/home/ubuntu/DiscordJS-V14-Bot-Template/src/class/ExtendedClient.js:37:9)
      at Object.<anonymous> (/home/ubuntu/DiscordJS-V14-Bot-Template/src/index.js:6:8)
      at Module._compile (node:internal/modules/cjs/loader:1218:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
      at Module.load (node:internal/modules/cjs/loader:1081:32)
      at Module._load (node:internal/modules/cjs/loader:922:12)
      at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
      at node:internal/main/run_main_module:23:47 {
    errno: -2,
    syscall: 'scandir',
    code: 'ENOENT',
    path: './src/commands/'
  }
}
```

**Comment by AbdoDev** [comment]
change it from './src/commands' to '../src/commands' it works for me

**Comment by yu4L** [comment]
I fixed it by removing the src part. 
I think linux doesnt like it when u are in src and u do ./src/...

😭
